In [3]:
import pandas as pd

In [5]:
data = pd.read_csv('archive/books.csv')

In [6]:
sel_cols = ['title', 'authors', 'original_publication_year', 'average_rating', 'ratings_count']
df = data[sel_cols]

# get Harry Potter books written by J.K. Rowling
# Get unique authors from the 'authors' column
authors = df.authors.unique()

# Filter authors to include only those written by J.K. Rowling
jkr = [i for i in authors if i.find('J.K. Rowling') != -1]

# Filter the DataFrame to include only books written by J.K. Rowling
jkr_books = df.loc[df.authors.isin(jkr)]

# Get unique titles from the filtered DataFrame
all_titles = jkr_books.title.unique()

# Filter titles to include only those containing 'Harry Potter and '
hp_titles = [i for i in all_titles if i.find('Harry Potter and ') != -1]

# Filter the DataFrame to include only Harry Potter books written by J.K. Rowling
hp_books = jkr_books.loc[jkr_books.title.isin(hp_titles)]

# Sort the DataFrame by the original publication year in ascending order
hp_books = hp_books.sort_values(by=['original_publication_year'], ascending=True)

display(hp_books)

,title,authors,original_publication_year,average_rating,ratings_count
1,Harry Potter and the Sorcerer's Stone (Harry P...,"J.K. Rowling, Mary GrandPré",1997.0,4.44,4602479
9,Harry Potter and the Chamber of Secrets (Harry...,"J.K. Rowling, Mary GrandPré",1998.0,4.37,1779331
6,Harry Potter and the Prisoner of Azkaban (Harr...,"J.K. Rowling, Mary GrandPré, Rufus Beck",1999.0,4.53,1832823
10,Harry Potter and the Goblet of Fire (Harry Pot...,"J.K. Rowling, Mary GrandPré",2000.0,4.53,1753043
8,Harry Potter and the Order of the Phoenix (Har...,"J.K. Rowling, Mary GrandPré",2003.0,4.46,1735368
12,Harry Potter and the Half-Blood Prince (Harry ...,"J.K. Rowling, Mary GrandPré",2005.0,4.54,1678823
11,Harry Potter and the Deathly Hallows (Harry Po...,"J.K. Rowling, Mary GrandPré",2007.0,4.61,1746574